version: '3.8'
services:
  backend: 
    container_name: cannassaince-ct
    build: .
    volumes:
      - .:/app
    ports: 
      - '8000:8000'
    depends_on:
      - db
  db: 
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
     - "5433:5432"
    volumes:
      - postgresdb:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes: 
  postgresdb: